# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 16:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bartender',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('shoe_size', models.CharField(default=0, max_length=10)),
                ('clothes_size', models.CharField(default=0, max_length=10)),
                ('works_in', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant')),
            ],
            options={
                'abstract': False,
            },
            bases=('authentication.user',),
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('shoe_size', models.CharField(default=0, max_length=10)),
                ('clothes_size', models.CharField(default=0, max_length=10)),
                ('works_in', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant')),
            ],
            options={
                'abstract': False,
            },
            bases=('authentication.user',),
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('shoe_size', models.CharField(default=0, max_length=10)),
                ('clothes_size', models.CharField(default=0, max_length=10)),
                ('works_in', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant')),
            ],
            options={
                'abstract': False,
            },
            bases=('authentication.user',),
        ),
    ]
