# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 19:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_auto_20160324_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('shoe_size', models.CharField(max_length=10)),
                ('clothes_size', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('authentication.user',),
        ),
        migrations.CreateModel(
            name='Bartender',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employee.Employee')),
            ],
            options={
                'abstract': False,
            },
            bases=('employee.employee',),
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employee.Employee')),
            ],
            options={
                'abstract': False,
            },
            bases=('employee.employee',),
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employee.Employee')),
            ],
            options={
                'abstract': False,
            },
            bases=('employee.employee',),
        ),
    ]
