# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('callableuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.CallableUser')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('shoe_size', models.CharField(default=0, max_length=10)),
                ('clothes_size', models.CharField(default=0, max_length=10)),
                ('password_change_count', models.IntegerField(default=0)),
                ('role', models.CharField(choices=[('WAITER', 'Waiter'), ('CHEF', 'Chef'), ('BARTENDER', 'Bartender')], default='WAITER', max_length=20)),
                ('works_in', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant')),
            ],
            options={
                'abstract': False,
            },
            bases=('authentication.callableuser',),
        ),
    ]
