# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_works_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='clothes_size',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='shoe_size',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='works_in',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
        ),
    ]
