# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_genericuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericuser',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
