# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='menu',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Menu'),
        ),
    ]
