# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='x',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='y',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
