# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20160409_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='food',
            name='restaurant',
        ),
    ]
