# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20160417_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
