# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_auto_20160418_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
