# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_confirmationtoken_user'),
        ('guest', '0002_guest_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='confirmation_token',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='authentication.ConfirmationToken'),
        ),
    ]
