# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_guest_confirmation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='confirmation_token',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.ConfirmationToken'),
        ),
    ]
